backend-ontomap/application/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ontoRequests/', include('ontoRequests.urls', namespace = 'ontoRequests')),
    url(r'^queries/', include('queries.urls', namespace = 'queries')),
]

backend-ontomap/ontoRequests/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from queries.models import Query
from rest_framework import routers, serializers, viewsets

from . import views

# class QuerySerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = Query
#         fields = ('name', 'query_content')

# class QueryViewSet(viewsets.ModelViewSet):
#     queryset = Query.objects.all()
#     serializer_class = QuerySerializer

# # Routers provide an easy way of automatically determining the URL conf
# router = routers.DefaultRouter()
# router.register(r'queries', QueryViewSet)


urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^retrieveQuery/$', views.retrieveQuery, name='retrieveQuery'),
    url(r'^executeQuery/$', views.executeQuery, name='executeQuery'),
    url(r'^changeOPType/$', views.changeOPType, name = 'changeOPType'),
    url(r'^addStrategyToTwo5D/$', views.addStrategyToTwo5D, name = 'addStrategyToTwo5D'),
    # url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

backend-ontomap/queries/urls.py
from django.conf.urls import url, include
from rest_framework import routers, serializers, viewsets
from . import views

urlpatterns = [
    # url(r'^queries', views.QueryViewSet.as_view(), name='queries api'),
    url(r'^$', views.get_queries, name='get queries'),
    url(r'^post$', views.post_query, name='post query'),
    url(r'^delete/(?P<query_id>[a-zA-Z0-9]+)/$', views.delete_query, name='delete query'),
    url(r'^execute-sparql$', views.execute_sparql, name='execute sparql query'),
    url(r'^api-auth/', include('rest_framework.urls'))
]

backend-ontomap/ontoRequests/models.py
from django.db import models
from django.utils.safestring import mark_safe

# Create your models here.
class Query(models.Model):
  name = models.CharField(max_length=100, null=False, blank=False)
  query_content = models.CharField(max_length=100000, null=False, blank=False)

  def __str__(self):
    return self.name

  def save(self, *args, **kwargs):
      # ecocase ID has to be unique (should probably make it a primary key)
    self.query_content = mark_safe(self.query_content)
    super(Query, self).save(*args, **kwargs)

backend-ontomap/ontoRequests/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse

from django.template import loader

from application.settings import conn

from src.coreFunc import makeListItem, runUpdateRequest, getVariables


import src.displayGraphs as dg
import urllib, base64
# from coreFunc import *

def index(request):
    # chooseFrom(['a', 'b', 'c', 'd', 'e', 'f', 'g'])
    # template = loader.get_template('ontoRequests/home.html')
    return render(request, 'ontoRequests/home.html', {})

def retrieveQuery(request):
    context = {'visibility' : request.POST['visib']}
    # print(request.POST)
    # return HttpResponse('La valeur de visibilité est ' + context['visibility'])
    # template = loader.get_template('ontoRequests/fromCong.temp.html')
    return render(request, 'ontoRequests/fromCong.temp.html', context)
    # return HttpResponse(template.render(context, request))

def executeQuery(request):
    global conn
    myReq = ''
    if request.POST['graph'] == 'yes' and len(getVariables(request.POST['query']))==2 :
        myReq = request.POST['query']
        myList = makeListItem(conn, myReq)
        keys = getVariables(myReq)
        context = {'isGraph' : True }
        try:
            print('1')
            graph = dg.makeGraphFromList(keys, myList)
            print('2')
            string = urllib.parse.quote(base64.b64encode(graph.read()))
            print('3')
            context['graph'] = string
            print('4')
            string.close()
            print('5')
        except:
            pass
        return render(request, 'ontoRequests/result.html', context)
    else:
        try:
            myReq = """SELECT ?docAddress
            { ?wkstp owl:Class stp:machining_workingstep .
             ?mop owl:Class stp:machining_operation .
             ?myTool owl:Class stp:machining_tool .
             ?docRef owl:Class stp:document .
             ?wkstp stp:machining_workingstep_has_operation ?mop .
             ?mop stp:machining_operation_has_tool ?myTool .
             ?myTool stp:machining_tool_has_id ?o .
             ?wkstp stp:element_has_document_reference ?docRef .
             ?docRef stp:document_has_name ?docAddress
            filter(?o = "%s"^^<http://www.w3.org/2001/XMLSchema#string>)
            }"""
            print(request.POST['toolID'])
            myReq = myReq%(request.POST['toolID'])
            context = {'isFinal' : True }
        except:
            myReq = request.POST['query']
            print('myReq: ', myReq)
            context = {'isFinal' : False }
        myList = makeListItem(conn, myReq)
        varsName = getVariables(myReq)
        context['isGraph'] = False
        context['varsName'] = varsName
        context['itemList'] = myList
        return render(request, 'ontoRequests/result.html', context)

def changeOPType(request):
    global conn
    OntoSTEPNC = "http://www.semanticweb.org/ontologies/OntoSTEP-NC#"
    conn.setNamespace('OntoSTEPNC', OntoSTEPNC)
    with open('mats/annotationsMOP.sparql') as filHandler:
        myReqs = filHandler.read().split('##')
        # 0 : Get all op / tool where op is of undefined type ("stp:machining_operation")
        # 1 : Get all possible kind of OP in STEP-NC (bar rough/finish distingo)
        # 2 : Update the base (1st arg : new OP_type ; 2nd arg : targetted op)
        # 3 : Get all mop of type two5D_milling_operation or sub classes
        # 4 : Get all possible kind of two5D_milling_strat
        # 5 : Insert the strategy descriptor
    try:
        a = request.POST['ChangeType'] != ''
    except:
        a = False
    if a :
        for key in request.POST:
            if "op_type" in key:
                if request.POST[key] != 'SKIP':

                    reqTmp = myReqs[2]%(conn.createURI(namespace = OntoSTEPNC, localname = request.POST[key].replace('op_type.', '')),
                                        conn.createURI(namespace = OntoSTEPNC, localname = key.replace('op_type.', '')))
                    print(runUpdateRequest(conn, reqTmp))
        pass  # Opérer le changement en base
    itemList = makeListItem(conn, myReqs[0])
    context = {'itemList' : itemList}
    context['classList'] = makeListItem(conn, myReqs[1])
    return render(request, 'ontoRequests/annotations_operations.html', context)

def addStrategyToTwo5D(request):
    global conn
    global conn
    OntoSTEPNC = "http://www.semanticweb.org/ontologies/OntoSTEP-NC#"
    conn.setNamespace('OntoSTEPNC', OntoSTEPNC)
    with open('mats/annotationsMOP.sparql') as filHandler:
        myReqs = filHandler.read().split('##')
        # 0 : Get all op / tool where op is of undefined type ("stp:machining_operation")
        # 1 : Get all possible kind of OP in STEP-NC (bar rough/finish distingo)
        # 2 : Update the base (1st arg : new OP_type ; 2nd arg : targetted op)
        # 3 : Get all mop of type two5D_milling_operation or sub classes
        # 4 : Get all possible kind of two5D_milling_strat
        # 5 : Insert the strategy descriptor
    try:
        a = request.POST['AddStrategy'] != ''
    except:
        a = False
    if a:
        for key in request.POST:
            if "strat" in key:
                if request.POST[key] != 'SKIP' :
                    reqTmp = myReqs[5]%(conn.createURI(namespace = OntoSTEPNC, localname = request.POST[key].replace('strat.', '')),
                                        conn.createURI(namespace = OntoSTEPNC, localname = key.replace('strat.', '')))
                    print(runUpdateRequest(conn, reqTmp))
                    # Do de dings
        pass
    itemList = makeListItem(conn, myReqs[3])
    myItems = []
    for i in itemList:
        try:
            graph = dg.makeGraphFromAdress(i[1], ['X', 'Y', 'Z'])
            string = urllib.parse.quote(base64.b64encode(graph.read()))
            myItems.append([i[0], string])
            string.close()
        except:
            pass
    context = {'itemList' : myItems}
    context['stratList'] = makeListItem(conn, myReqs[4])
    # Display trajectory along the name and possible strategies
    return render(request, 'ontoRequests/op_strategy.html', context)

backend-ontomap/ontoRequests/templates/ontoRequests/annotations_operations.html
<!DOCTYPE HTML>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Annotations</title>
</head>

<body>

	<header>
		<h1>Annotation des opérations selon les sous-catégories définies dans STEP-NC</h1>
	</header>

	<section>
        <div>
            <form action = "{% url 'ontoRequests:changeOPType' %}" method="post">
            {% csrf_token %}
            <input type="text" id="ChangeType" name = "ChangeType" value="ChangeType" visibility = "hidden" />
                <table>
                    <tr>
                        <th>Operation</th>
                        <th>Outil</th>
                        <th>Selection d'OP</th>
                    </tr>
                    {% for i in itemList %}
                        <tr{% if forloop.counter|divisibleby:2 %} style="background-color : #DDDDDD" {% endif %}>
                            <td>{{ i.0 }}</td>
                            <td>{{ i.1 }}</td>
                            <td>
                                <SELECT name = "op_type.{{ i.0 }}">
                                    <option selected>SKIP</option>
                                    {% for j in classList %}
                                        <option>{{ j }}</option>
                                    {% endfor %}
                                </SELECT>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <input type="submit" value = "Mettre à jour" />
            </form>
        </div>
	</section>

	<footer>
		<p>UTC - Roberval 2018</p>
	</footer>

</body>

</html>

backend-ontomap/ontoRequests/templates/ontoRequests/fromCong.temp.html
<!DOCTYPE HTML>
<!-- {% csrf_token %} -->
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Champ de requête OntoMAP</title>
</head>

<body>

	<header>
		<h1>Page de saisie de requêtes</h1>
	</header>

	<section>
		<form action="{% url 'ontoRequests:executeQuery' %}" method="post">
		{% csrf_token %}
			<textarea rows = "8" cols = "150" name = "query" style = "visibility:{{ visibility }}">Type your request in here.</textarea><br />
            <input type="radio" name="graph" id="no" value = "no" checked = "checked"/>
			<label for = "visible">Table</label><br />

			<input type="radio" name="graph" id="yes" value = "yes"/>
			<label for = "visible">Graphe</label><br />
			<input type="submit" value="Lancer" />
		</form>
	</section>

	<footer>
		<p>UTC - Roberval 2018</p>
	</footer>

</body>

</html>

backend-ontomap/ontoRequests/templates/ontoRequests/home.html
<!DOCTYPE HTML>
<!-- {% csrf_token %} -->
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Accueil OntoMAP</title>
</head>

<body>

	<header>
		<h1>Bienvenue sur la page d'accueil du démonstrateur OntoMAP</h1>
	</header>

	<section>

		<form action="{% url 'ontoRequests:retrieveQuery' %}" method="post">
			{% csrf_token %}
			<!-- <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br /> -->

			<input type="radio" name="visib" id="visible" value = "visible" checked = "checked"/>
			<label for = "visible">Visible</label><br />

			<input type="radio" name="visib" id="hidden" value = "hidden"/>
			<label for = "visible">Caché</label><br />

			<input type="submit" value = "Lancer" />
		</form>
        <a href = "{% url 'ontoRequests:changeOPType' %}">Page d'annotations</a><br />
        <a href = "{% url 'ontoRequests:addStrategyToTwo5D' %}">Sélectionner la stratégie utilisée</a>

	</section>

	<footer>
		<p>UTC - Roberval 2018</p>
	</footer>

</body>

</html>

backend-ontomap/ontoRequests/templates/ontoRequests/op_strategy.html
<!DOCTYPE HTML>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Annotations</title>
</head>

<body>

	<header>
		<h1>Annotation des opérations selon les stratégies définies dans STEP-NC</h1>
	</header>

	<section>
        <div>
            <form action = "{% url 'ontoRequests:addStrategyToTwo5D' %}" method="post">
            {% csrf_token %}
            <input type="text" id="AddStrategy" name = "AddStrategy" value="AddStrategy" style="display:none" />
                <table>
                    <tr>
                        <th>Nom</th>
                        <th>Trajectoire</th>
                        <th>Stratégie</th>
                    </tr>
                    {% for i in itemList %}
                        <tr{% if forloop.counter|divisibleby:2 %} style="background-color : #DDDDDD" {% endif %}>
                            <td>{{ i.0 }}</td>
                            <td><img alt="{{ i.0 }}" src="data:image/png;base64,{{ i.1 }}" /></td>
                            <td>
                                <SELECT name = "strat.{{ i.0 }}">
                                    <option selected>SKIP</option>
                                    {% for j in stratList %}
                                        <option>{{ j }}</option>
                                    {% endfor %}
                                </SELECT>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <input type="submit" value = "Mettre à jour" />
            </form>
        </div>
	</section>

	<footer>
		<p>UTC - Roberval 2018</p>
	</footer>

</body>

</html>

backend-ontomap/ontoRequests/templates/ontoRequests/result.html
<!DOCTYPE HTML>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Résultats OntoMAP</title>
</head>

<body>

	<header>
		<h1>Affichage des résultats de requête.</h1>
	</header>

	<section>

		<div>
            {% if isGraph %}
                <img alt="myGraph" src="data:image/png;base64,{{ graph }}" />
            {% else %}
                {% if varsName|length > 1 %}
                    <table>
                        <tr>
                            {% for var in varsName %}
                                <th>{{ var }}</th>
                            {% endfor %}
                        </tr>
                        {% for i in itemList %}
                            <tr style="background-color : {% cycle '#DDDDDD' '#FFFFFF' %} "><!--{{ i }}-->
                                {% for j in i %}
                                    <td>{{ j }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    {% if not isFinal %}
                        <form action="{% url 'ontoRequests:executeQuery' %}" method="post">
                            {% csrf_token %}
                            {% for i in itemList %}
                                <input type="radio" name="toolID" id="tool{{forloop.counter}}" value="{{ i }}" {% if forloop.counter == 1 %}checked = "checked"{% endif %} />
                                <label for="tool{{forloop.counter}}">{{ i }}</label><br />
                            {% endfor %}
                            <input type="submit" value = "Seléctionner" />
                    {% else %}
                        <ul>
                            {% for i in itemList %}
                                <li>{{ i }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endif %}
            {% endif %}
		</div>

	</section>

	<footer>
		<p>UTC - Roberval 2018</p>
	</footer>

</body>

</html>